### ISSUE TITLE
openMINDS.version_manager.init() hangs

### ISSUE THREAD

**Issue by maciej-jedynak** [HumanBrainProject/openMINDS_generator#24]
The code:

```
import openMINDS
import openMINDS.version_manager

openMINDS.version_manager.init()
```

The error:
```

Target directory will created
Cloning openMINDS to target directory
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    main()
  File "test.py", line 9, in main
    openMINDS.version_manager.init()
  File "/home/maciek/anaconda3/lib/python3.7/site-packages/openMINDS/version_manager.py", line 116, in init
    update_openMINDS(target_dir)
  File "/home/maciek/anaconda3/lib/python3.7/site-packages/openMINDS/version_manager.py", line 48, in update_openMINDS
    repo = git.Repo.clone_from(REPO_URL, target_directory, branch='documentation')
  File "/home/maciek/anaconda3/lib/python3.7/site-packages/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/home/maciek/anaconda3/lib/python3.7/site-packages/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/maciek/anaconda3/lib/python3.7/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/home/maciek/anaconda3/lib/python3.7/site-packages/git/cmd.py", line 501, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=documentation https://github.com/HumanBrainProject/openMINDS/ /home/maciek/.openMINDS_python
  stderr: 'Cloning into '/home/maciek/.openMINDS_python'...
POST git-upload-pack (477 bytes)
error: RPC failed; curl 16 Error in the HTTP2 framing layer
fatal: the remote end hung up unexpectedly
```

**Comment by maciej-jedynak** [comment]
As says the error "fatal: the remote end hung up unexpectedly", this problem must have been due to the server side, now it works without any changes on the client side.
